{{- if .Values.profiseeRunTime.deployIngressRule }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: profisee-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    #kubernetes.io/ingress.class: azure/application-gateway
    nginx.ingress.kubernetes.io/proxy-body-size: "0" 
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers: "4 256k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "256k"
    nginx.ingress.kubernetes.io/client-header-buffer-size: "64k"
    #nginx.ingress.kubernetes.io/http2-max-field-size: "16k"
    #nginx.ingress.kubernetes.io/http2-max-header-size: "128k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "8 64k"
    nginx.ingress.kubernetes.io/client_body_buffer_size: "64k"
    {{- if .Values.profiseeRunTime.isPaaS }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- end }}
    
    {{- if .Values.profiseeRunTime.useLetsEncrypt }}
    cert-manager.io/cluster-issuer: letsencrypt
    {{- end }}

spec:
  tls:
  - hosts:
    - {{.Values.profiseeRunTime.externalDnsName}}
    secretName: profisee-tls-ingress
  rules:
  - host: {{.Values.profiseeRunTime.externalDnsName}}
    http:
      paths:
      {{- if .Values.profiseeRunTime.isPaaS }}
      - path: /(.*)
      {{- else }}
      - path: /{{.Values.profiseeRunTime.webAppName}}/?(.*)$
      {{- end }}
        pathType: Prefix
        backend:
          service:
            name: profisee-service
            port: 
              number: 80
{{- end }}

