{{- if .Values.cloud.azure.isProvider -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: profisee-purview
data:
  ProfiseePurviewUrl: {{.Values.cloud.azure.purview.url | b64enc | quote}}
  ProfiseePurviewTenantId: {{.Values.cloud.azure.purview.tenantId | b64enc | quote}}
  ProfiseePurviewClientId: {{.Values.cloud.azure.purview.clientId | b64enc | quote}}
  ProfiseePurviewClientSecret: {{.Values.cloud.azure.purview.clientSecret | b64enc | quote}}
{{- end }}
