{{- if not .Values.cloud.azure.useKeyVault -}}
{{- if not .Values.profiseeRunTime.useLetsEncrypt -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: profisee-tls-ingress
data:
  tls.crt: {{.Values.tlsCert | b64enc }}
  tls.key: {{.Values.tlsKey | b64enc }}
{{- end }}
{{- end }}
