apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: profisee-filerepository-password
data:
  ProfiseeAttachmentRepositoryUserPassword: {{.Values.profiseeRunTime.fileRepository.password | b64enc | quote}}
