{{- if not .Values.cloud.azure.useKeyVault -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: profisee-sql-username
data:
  ProfiseeSqlUserName: {{.Values.sqlServer.userName | b64enc | quote}}
{{- end }}
