apiVersion: v1
kind: Service
metadata:
  name: profisee-service
  labels: 
    app: profisee
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
      app: profisee
  type: ClusterIP
  clusterIP: None
