controller: 
  extraArgs: 
    default-ssl-certificate: default/aks-ingress-tls
  nodeSelector: 
    beta.kubernetes.io/os: linux
  replicaCount: 1
  service: 
    loadBalancerIP: 0.0.0.0
  config:
    proxy-buffering: "off"
    proxy-buffer-size: "16k"
    proxy-connect-timeout: "5400"
    proxy-send-timeout: "5400"
    proxy-read-timeout: "5400"
    proxy-next-upstream: "off"
    proxy-request-buffering: "off"
    client-header-buffer-size: "64k"
    http2-max-field-size: "16k"
    http2-max-header-size: "128k"
    large-client-header-buffers: "8 64k"
    client_body_buffer_size: "64k"
defaultBackend: 
  nodeSelector: 
    beta.kubernetes.io/os: linux
